/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProjekJFrame.view;

import javax.swing.JFrame;

/**
 *
 * @author rakhacimano
 */
public class View extends javax.swing.JFrame {

    public static String previousViewName;
    public static String currentViewName;

    public View() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public void setPreviousView(String previousView) {
        View.previousViewName = previousView;
    }

    public String getPreviousView() {
        return previousViewName;
    }

    public void setCurrentView(String currentView) {
        View.currentViewName = currentView;
    }

    public String getCurrentView() {
        return currentViewName;
    }

    public void setFrame(String viewName) {
        switch (viewName) {
            case "View One":
                showView(new ViewOne());
                break;
            case "View Two":
                showView(new ViewTwo());
                break;
            case "View Three":
                showView(new ViewThree());
                break;
            case "View Four":
                showView(new ViewFour());
                break;
            case "View Five":
                showView(new ViewFive());
                break;
            case "View Six":
                showView(new ViewSix());
                break;
            case "View Seven":
                showView(new ViewSeven());
                break;
            case "View Eight":
                showView(new ViewEight());
                break;
            case "View Nine":
                showView(new ViewNine());
                break;
            case "View Ten":
                showView(new ViewTen());
                break;
            default:
                System.out.println("Error");
        }
        dispose();
    }

    public void showView(JFrame view) {
        view.setVisible(true);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonViewFive = new javax.swing.JButton();
        labelCurrentView = new javax.swing.JLabel();
        buttonViewSix = new javax.swing.JButton();
        buttonViewSeven = new javax.swing.JButton();
        buttonViewEight = new javax.swing.JButton();
        buttonViewNine = new javax.swing.JButton();
        labelPreviousView = new javax.swing.JLabel();
        buttonViewTen = new javax.swing.JButton();
        textPreviousView = new javax.swing.JLabel();
        buttonViewOne = new javax.swing.JButton();
        buttonViewThree = new javax.swing.JButton();
        buttonViewTwo = new javax.swing.JButton();
        buttonViewFour = new javax.swing.JButton();
        textCurrentView = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonViewFive.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonViewFive.setText("5");
        buttonViewFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonViewFiveActionPerformed(evt);
            }
        });

        labelCurrentView.setText("Current View");

        buttonViewSix.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonViewSix.setText("6");
        buttonViewSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonViewSixActionPerformed(evt);
            }
        });

        buttonViewSeven.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonViewSeven.setText("7");
        buttonViewSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonViewSevenActionPerformed(evt);
            }
        });

        buttonViewEight.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonViewEight.setText("8");
        buttonViewEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonViewEightActionPerformed(evt);
            }
        });

        buttonViewNine.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonViewNine.setText("9");
        buttonViewNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonViewNineActionPerformed(evt);
            }
        });

        labelPreviousView.setText("Previous View");

        buttonViewTen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonViewTen.setText("10");
        buttonViewTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonViewTenActionPerformed(evt);
            }
        });

        textPreviousView.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        textPreviousView.setText("View");

        buttonViewOne.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonViewOne.setText("1");
        buttonViewOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonViewOneActionPerformed(evt);
            }
        });

        buttonViewThree.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonViewThree.setText("3");
        buttonViewThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonViewThreeActionPerformed(evt);
            }
        });

        buttonViewTwo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonViewTwo.setText("2");
        buttonViewTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonViewTwoActionPerformed(evt);
            }
        });

        buttonViewFour.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonViewFour.setText("4");
        buttonViewFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonViewFourActionPerformed(evt);
            }
        });

        textCurrentView.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        textCurrentView.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        textCurrentView.setText("View");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonViewSix, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(buttonViewSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(buttonViewEight, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(buttonViewNine, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(buttonViewTen, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonViewOne, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(buttonViewTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(buttonViewThree, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(buttonViewFour, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(buttonViewFive, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelPreviousView)
                                .addGap(61, 61, 61))
                            .addComponent(textPreviousView, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(labelCurrentView))
                            .addComponent(textCurrentView, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCurrentView)
                    .addComponent(labelPreviousView))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCurrentView)
                    .addComponent(textPreviousView))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonViewOne, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonViewTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonViewThree, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonViewFour, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonViewFive, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonViewSix, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonViewSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonViewEight, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonViewNine, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonViewTen, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonViewOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonViewOneActionPerformed
        setFrame("View One");
    }//GEN-LAST:event_buttonViewOneActionPerformed

    private void buttonViewTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonViewTwoActionPerformed
        setFrame("View Two");
    }//GEN-LAST:event_buttonViewTwoActionPerformed

    private void buttonViewThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonViewThreeActionPerformed
        setFrame("View Three");
    }//GEN-LAST:event_buttonViewThreeActionPerformed

    private void buttonViewFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonViewFourActionPerformed
        setFrame("View Four");
    }//GEN-LAST:event_buttonViewFourActionPerformed

    private void buttonViewFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonViewFiveActionPerformed
        setFrame("View Five");
    }//GEN-LAST:event_buttonViewFiveActionPerformed

    private void buttonViewSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonViewSixActionPerformed
        setFrame("View Six");
    }//GEN-LAST:event_buttonViewSixActionPerformed

    private void buttonViewSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonViewSevenActionPerformed
        setFrame("View Seven");
    }//GEN-LAST:event_buttonViewSevenActionPerformed

    private void buttonViewEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonViewEightActionPerformed
        setFrame("View Eight");
    }//GEN-LAST:event_buttonViewEightActionPerformed

    private void buttonViewNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonViewNineActionPerformed
        setFrame("View Nine");
    }//GEN-LAST:event_buttonViewNineActionPerformed

    private void buttonViewTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonViewTenActionPerformed
        setFrame("View Ten");
    }//GEN-LAST:event_buttonViewTenActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton buttonViewEight;
    public javax.swing.JButton buttonViewFive;
    public javax.swing.JButton buttonViewFour;
    public javax.swing.JButton buttonViewNine;
    public javax.swing.JButton buttonViewOne;
    public javax.swing.JButton buttonViewSeven;
    public javax.swing.JButton buttonViewSix;
    public javax.swing.JButton buttonViewTen;
    public javax.swing.JButton buttonViewThree;
    public javax.swing.JButton buttonViewTwo;
    private javax.swing.JLabel labelCurrentView;
    private javax.swing.JLabel labelPreviousView;
    public javax.swing.JLabel textCurrentView;
    public javax.swing.JLabel textPreviousView;
    // End of variables declaration//GEN-END:variables
}
